### ISSUE TITLE
Engine support for animation?

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5677]
Not sure if this is out of scope, but engine support for unit sprite animations would be cool, even if not enabled by default.

E.G.:

![8nM4Np](https://user-images.githubusercontent.com/37680486/141689062-4bbf7c0c-b823-40df-a423-342a07268ed6.gif)

(From: https://yajohn.itch.io/historical-hex-tiles1)

Attack would be easy enough (in principle, not in implementation). Just play the right spritesheet, and flip it if needed. Or let the mod decide whether to flip it. Movement could be trickier.

I guess there would be two main definitions for modders to implement every action:
1. Frames and frame timings.
2. Sprite position keyframes (for absolute-positioned animations like unit attack and idle) and maximum movement rate keyframes (for variable-length and position-changing animations, like unit movement).

Previous mention: #3910

**Comment by yairm210** [comment]
Basically, nope
Sounds ghastly to implement and ghastly to create
Entirely out of scope

**Comment by logicminimal** [comment]
> Basically, nope
> Sounds ghastly to implement and ghastly to create
> Entirely out of scope

actually, i think it might not be that hard, in the end, all we need is the end texture. like we could create a wrapper class that will handle frames and array<textureregion> for us, or if we want to be precise woth timing we can write a wrapper around the animation class of libgdx, which i did. the main thing is, in my implementation, you need to call
 `unit.animWrapper.apply{update(timeDelta)}.GetTexture `

or just


`unit.AnimWrapper.getTexture(timeDelta)`

i dont know how hard this would be to implement, but if we care about how easy it is to integrate this into the game, in unitSprite calls we can instead call the draw function of the animationWrapper with the delta as an argument, offloading the code work to the inner workings of the unit classes animationWrapper

**Comment by logicminimal** [comment]
> Basically, nope
> Sounds ghastly to implement and ghastly to create
> Entirely out of scope

actually, i think it might not be that hard, in the end, all we need is the end texture. like we could create a wrapper class that will handle frames and array<textureregion> for us, or if we want to be precise woth timing we can write a wrapper around the animation class of libgdx, which i did. the main thing is, in my implementation, you need to call
 `unit.animWrapper.apply{update(timeDelta)}.GetTexture `

or just


`unit.AnimWrapper.getTexture(timeDelta)`

i dont know how hard this would be to implement, but if we care about how easy it is to integrate this into the game, in unitSprite calls we can instead call the draw function of the animationWrapper with the delta as an argument, offloading the code work to the inner workings of the unit classes animationWrapper

**Comment by xlenstra** [comment]
Feel free to PR it and I'll take a look at it.
Other questions you'd have to deal with:
- How are the different frames denoted in json format so they can easily be modded by audio-visual mod makers?
- Do you have idle animations? If so, how do you prevent your game from crawling through a halt as your ~150 units are each redrawing their animation frames every 1/7th of a second?
- Do you want to center the camera on each combat taking place outside of your turn to show animations for defending?
- Who will make all the animations for all the different units for all the different nations?

**Comment by logicminimal** [comment]
> Feel free to PR it and I'll take a look at it.
> Other questions you'd have to deal with:


> - How are the different frames denoted in json format so they can easily be modded by audio-visual mod makers?

in my personal implementation i keep an array<Float> and input it to my animationWrapper class, which could be integrated easily to json

> - Do you have idle animations? If so, how do you prevent your game from crawling through a halt as your ~150 units are each redrawing their animation frames every 1/7th of a second?

options>visual>allow idle unit animations

> - Do you want to center the camera on each combat taking place outside of your turn to show animations for defending?

just do whatever civ 5 or civ 6 does (with ability to make move or attack anims faster(note that move and attack anims still take a lot of time in turn computing phase, which most players combat by enabling quick movement and quick combat))

> - Who will make all the animations for all the different units for all the different nations?

¯\_(ツ)_/¯

**Comment by will-ca** [comment]
> * How are the different frames denoted in json format so they can easily be modded by audio-visual mod makers?

Would depend on what works and is performant with the capabilities of LibGDX, but I'd look at defining "actions" somewhat similarly to what CSS, GLTF, and other DCC stuff do.

E.G.

```yaml
UnitAnimActions:
  Knight_Attack_NorthEast:
    time: absolute
    mode: playonce
    duration: 0.8
    interpolate: clampedbezier
    frames:
    - {path: sprites/KnightAttackNE_0.png, time: 0.0, flip: false, offset: [0, 0]} #Instead of images and times per frame, could also define one spritesheet and the amount to shift it by every elapsed unit of time.
    - {path: sprites/KnightAttackNE_1.png, time: 0.2, flip: false, offset: [0.15, 0.1]}
    - {path: sprites/KnightAttackNE_2.png, time: 0.4, flip: false, offset: [0.25, 0.2]}
    - {path: sprites/KnightAttackNE_0.png, time: 0.8, flip: false, offset: [0, 0]}
  Knight_Move_SouthWest:
    time: absolute
    mode: loop
    duration: 0.5
    interpolate: clampedbezier
    #blend_in: 0.4
    #blend_out: 0.4 #E.G.: Top down perspective. All sprites point up, but different directions have different `"rotation"`. Allows smooth turning for top-down perspective.
    frames:
    - {path: sprites/KnightAttackSW_0.png, time: 0.0, flip: false, maxtravel: 0.5} #Since move length is unknown, max travel instead of offset.
    - {path: sprites/KnightAttackSW_1.png, time: 0.2, flip: false, maxtravel: 0.3} #Lower max travel to fit lower frame duration.
    - {path: sprites/KnightAttackSW_1.png, time: 0.3, flip: false, maxtravel: 0.5}
    multipliers:
    - time: relative_distance #Means time values are defined relative to the fraction of total distance travelled.
      mode: playonce
      duration: null
      interpolate: linear
      frames:
      - {time: 0, timescale: 0.3, maxtravel: 0.3}
      - {time: 0.1, timescale: 1, maxtravel: 1} #Start out slow, accelerate to max speed by 10% of travel distance, then slow down after 90%.
      - {time: 0.9, timescale: 1, maxtravel: 1}
      - {time: 1, timescale: 0.3, maxtravel: 0.3} #Can't have zero maxtravel, or it will never finish.
```

I suppose it would also be pretty straightforwards to write exporters for E.G. GIMP to convert GIF timings into something like this format, or even Blender to automatically render out the frames and export the JSON path/timing/offset definitions for all six hexagonal movement directions given a 3D model and rig of known structure. (I'd estimate maybe 100, max 200 LoC for a minimum working Blender exporter. (In reality I might well go over 1,000, but only because of self-destructive scope creep.))

> * Do you have idle animations? If so, how do you prevent your game from crawling through a halt as your ~150 units are each redrawing their animation frames every 1/7th of a second?

Hard cap on number of simultaneously playing animations, plus restricting to visible units.

```Kotlin
fun getNextIdleAnimations(): List<MapUnit> {
    return random.SelectCount(
        items = units.filter{ mapHolder.visible(it) },
        count = min(units.size*0.3, 6)
    ) //The units in the returned list then get spread out over the next X seconds, after which a new batch is chosen.
}
```

Performance isn't exactly an unsolved problem in computer graphics. The trick is to usually render only what the user can see. Motion attracts eyes, so you really only need one or two things moving on-screen at any given time to liven up a scene. The "`6`" in my example code above is almost being generous. And you of course don't need to bother rendering anything that the user *can't* see, which means that most of the time it won't even be 15 units to choose from, much less 150.

(If we ignore the interpolation I put in the JSON/YAML example, or hard-code different update behaviour for `constant` interpolation as a default class— Note to self.— Then we're also looking at sprite updates only every couple hundred milliseconds, which seems… Not free, but close to free.)

…Or hell, the game's OpenGL-based, right? So sprite swapping/frame playback should go in the shader, then.

> * Do you want to center the camera on each combat taking place outside of your turn to show animations for defending?

Yes. I would implement a replay stage that is displayed before each turn, akin to what Civ and Polytopia have, toggleable in (Game) Options and possibly skippable per turn and per unit. It's important tactical information.

> * Who will make all the animations for all the different units for all the different nations?

The link in my first comment here claims 48 unit and 6 animal "Attack, Hit, and Dead" animations available for $2. Not sure about license, but the artist seems cooperative, and I'm sure there are others out there. So could always buy the artwork.

If not that, then I'd just make them myself. Cheapest way for me to do it would probably be to render out units in 3D and then algorithmically generate pixel art from the colour/depth/normal data. …Really only need to make 3D actions for three types of units— Legged, Mounted, Mechanized— I think, and then swap out the mesh and textures. Bonus: I would have to write the 3D exporter as part of that, so if I clean that up and share it then there's a tool for other artists too.

So `len(gameInfo.ruleSet.units) >>> 122` unit types multiplied by `6` hexagonal directions, for at least 732 sprite animations per action, gets reduced to just three animated rigs and six automated render directions, of which the former is a couple hours of work and the latter is just a couple dozen lines of Python. Not totally sure how I'd get the meshes and textures for the rigs for each unit type. I might start by projecting processed versions of the current pixel art onto a handful of simple base models, if colour proves to be a big factor in their distinctiveness. Then again, as I'd downsample it all to pixel art anyway, extra detail isn't needed and is in fact harmful, so I could even handpaint the textures, maybe finishing each in a minute or two with an efficient workflow established. …VRAM might be an issue, but honestly with small-to-medium-sized pixel art it'd still only be a couple dozen megabytes even with thousands of unique RGBA sprite animations. Also don't strictly *need* unique sprites for all 122 units, since pixel sprites aren't even enabled by default per last I checked. Could just have one humanoid, one mounted, one mechanized, and a handful of naval spritesheets, deciding that static distinctiveness is a worthwhile tradeoff for unit animations.

If not that, then I'd forego making sprite frames completely, and just generate placeholder actions using the current static sprites with the `"offset"`, `"maxtravel"`, and `"flip"` definitions. This would bring Unciv up to the same level as Polytopia graphically, which also uses static pixel sprites but shows them sliding around the map when moving and attacking, bouncing when injured, etc. With engine support in place, making thousands of unique animated sprites would then be left to modders or a follow-up PR.

---

IMO None of the problems are unsolved, or even that challenging on an implementation and maintenance basis. It's just a very different area of development from most of the existing game code, and indeed a lot of work to implement. …Learning from my debacle with the scripting API, I'd probably start with a minimum working implementation consisting of some kind of `UnitActionAnimator` class that takes over to show a hard-coded sliding motion during unit movement, then instantiate it in a separate PR to play back visible foreign actions at the start of each player turn, and only then add support for JSON-defined sprite frames, a default animation set, and GPU playback.

As for me, I'm hoping to exercise a shred of self-restraint, and not take on this large and highly unprofitable engineering effort at least until/unless I've already gotten my existing Unciv-related large and highly unprofitable engineering effort ready to merge, however many weeks or months that may be from now.
