### ISSUE TITLE
Feature request: add Java 17 support for unittests and code checks as well (the game seems to works with it)

### ISSUE THREAD

**Issue by CrsiX** [yairm210/Unciv#8835]
Currently, running the code checks and the unit tests on the code base requires Java 11. Using Java 17 causes the runs to fail. Specifically, the two CI steps are affected:
- `./gradlew check`
- `./gradlew --no-build-cache cleanTest test tests:test`

Note that the game and the server seems to work, so this is not too high priority. Additionally, Java 11 is the LTS version; it gets updates until at least late 2024 (some distributions even longer).

You can verify this by e.g. adding a matrix for the CI jobs:

```yaml
jobs:
  build:
    strategy:
      matrix:
        java_version:
          - 11
          - 17

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: temurin
          java-version: ${{ matrix.java_version }}
```
